// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"NUUN_Base","status":true,"description":"共通処理","parameters":{}},
{"name":"WeaponArmorTypeExtend","status":true,"description":"武具タイプ拡張プラグイン","parameters":{"equipConditionType":"1"}},
{"name":"ARTM_PlayerSensorMZ","status":true,"description":"プレイヤー探索プラグイン(MZ移植版)","parameters":{"探索設定":"====================================","Sensor_Switch":"D","Lost_Sensor_Switch":"","Both_Sensor":"false","Terrain_Decision":"true","Auto_Sensor":"true","Event_Decision":"false","Region_Decision":"[]","Real_Range_X":"0.000","Real_Range_Y":"0.000","視界設定":"====================================","Range_Visible":"true","Range_Color":"white","Range_Opacity":"30","Range_Position":"1","Player_Found":"{\"Ballon\":\"0\",\"Se\":\"{\\\"Name\\\":\\\"\\\",\\\"Volume\\\":\\\"90\\\",\\\"Pitch\\\":\\\"100\\\",\\\"Pan\\\":\\\"0\\\"}\",\"Common_Event\":\"0\",\"Delay\":\"0\"}","Player_Lost":"{\"Ballon\":\"0\",\"Se\":\"{\\\"Name\\\":\\\"\\\",\\\"Volume\\\":\\\"90\\\",\\\"Pitch\\\":\\\"100\\\",\\\"Pan\\\":\\\"0\\\"}\",\"Common_Event\":\"0\",\"Delay\":\"0\"}","マップ設定":"====================================","Tracking_Priority":"false","Follower_Through":"false","Location_Reset":"false","Found_Keep":"false"}},
{"name":"NUUN_StatusParamEX","status":true,"description":"アクターステータスの最大値設定","parameters":{"limitHP":"-1","limitMP":"-1","limitTP":"-1","limitAtk":"-1","limitDef":"-1","limitMat":"-1","limitMdf":"-1","limitAgi":"-1","limitLuk":"-1"}},
{"name":"MNKR_TimingInvokeCommonMZ","status":true,"description":"場所移動時・戦闘開始/終了時にコモンイベントを実行します。","parameters":{"TransferCommonID":"0","BattleStartCommonID":"0","BattleEndCommonID":"1"}},
{"name":"GameSpeedX10_LoopSwitch","status":true,"description":"ゲーム進行速度を10倍にする（スイッチでON/OFF可能）プラグイン v1.3 by 鈴木","parameters":{"SpeedUpSwitchId":"1"}},
{"name":"SZ_MaxStackPlugin","status":false,"description":"特定アイテムだけ所持上限を99個以上にできるプラグイン（メモ欄制御） - by 鈴木","parameters":{}},
{"name":"NUUN_AddDropItems","status":true,"description":"ドロップアイテム追加","parameters":{}},
{"name":"Double_drop_items","status":true,"description":"NUUN_AddDropItemsの追加ドロップを倍化するプラグイン","parameters":{"DoubleStateId":"35"}},
{"name":"Yoshida_MaxStackExtension","status":true,"description":"所持アイテムの上限を特定アイテムの所持で拡張する（吉田）ver1.0","parameters":{}}
];
